src/Entity/Training.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TrainingRepository")
 */
class Training
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=128)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=128)
     */
    private $location;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="date")
     */
    private $date_start;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_end;

    /**
     * @ORM\Column(type="string", length=128)
     */
    private $company;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $companyLink;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $list_order;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDateStart(): ?\DateTimeInterface
    {
        return $this->date_start;
    }

    public function setDateStart(\DateTimeInterface $date_start): self
    {
        $this->date_start = $date_start;

        return $this;
    }

    public function getDateEnd(): ?\DateTimeInterface
    {
        return $this->date_end;
    }

    public function setDateEnd(?\DateTimeInterface $date_end): self
    {
        $this->date_end = $date_end;

        return $this;
    }

    public function getCompany(): ?string
    {
        return $this->company;
    }

    public function setCompany(string $company): self
    {
        $this->company = $company;

        return $this;
    }

    public function getCompanyLink(): ?string
    {
        return $this->companyLink;
    }

    public function setCompanyLink(?string $companyLink): self
    {
        $this->companyLink = $companyLink;

        return $this;
    }

    public function __toString()
    {
        return $this->title;
    }

    public function getListOrder(): ?int
    {
        return $this->list_order;
    }

    public function setListOrder(?int $list_order): self
    {
        $this->list_order = $list_order;

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Repository\SoftRepository;
use App\Repository\SkillRepository;
use App\Repository\ContactRepository;
use App\Repository\AptitudeRepository;
use App\Repository\InterestRepository;
use App\Repository\LanguageRepository;
use App\Repository\TrainingRepository;
use App\Repository\PortfolioRepository;
use App\Repository\ExperienceRepository;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class MainController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index(
        ExperienceRepository $expRepo,
        TrainingRepository $trainingRepo,
        SkillRepository $skillRepo,
        AptitudeRepository $aptRepo,
        InterestRepository $interestRepo,
        ContactRepository $contactRepo,
        PortfolioRepository $portfolioRepo,
        SoftRepository $softRepo,
        LanguageRepository $langRepo
    )
    {
        $info = file_get_contents($this->getParameter('data_directory') . '/data.json');
        $info = \json_decode($info);
        
        $experiences = $expRepo->findBy([], ['list_order' => 'ASC']);
        $trainings = $trainingRepo->findBy([], ['list_order' => 'ASC']);
        $skills = $skillRepo->findBy([], ['level' => 'DESC']);
        $aptitudes = $aptRepo->findAll();
        $interests = $interestRepo->findBy([], ['list_order' => 'ASC']);
        $contacts = $contactRepo->findAll();
        $portfolios_pro = $portfolioRepo->findBy(['type' => 'pro'], ['list_order' => 'ASC']);
        $portfolios_perso = $portfolioRepo->findBy(['type' => 'perso'], ['list_order' => 'ASC']);
        $softs = $softRepo->findAll();
        $languages = $langRepo->findAll();
        
        return $this->render('main/index.html.twig', [
            'info' => $info,
            'experiences' => $experiences,
            'trainings' => $trainings,
            'skills' => $skills,
            'aptitudes' => $aptitudes,
            'interests' => $interests,
            'contacts' => $contacts,
            'portfolios_pro' => $portfolios_pro,
            'portfolios_perso' => $portfolios_perso,
            'softs' => $softs,
            'languages' => $languages,
        ]);
    }

    /**
     * @Route("/pdf", name="home_pdf")
     */
    public function pdf(
        ExperienceRepository $expRepo,
        TrainingRepository $trainingRepo,
        SkillRepository $skillRepo,
        AptitudeRepository $aptRepo,
        InterestRepository $interestRepo,
        ContactRepository $contactRepo,
        PortfolioRepository $portfolioRepo,
        SoftRepository $softRepo,
        LanguageRepository $langRepo
    )
    {
        $info = file_get_contents($this->getParameter('data_directory') . '/data.json');
        $info = \json_decode($info);
        
        $experiences = $expRepo->findBy([], ['list_order' => 'ASC']);
        $trainings = $trainingRepo->findBy([], ['list_order' => 'ASC']);
        $skills = $skillRepo->findBy([], ['level' => 'DESC']);
        $aptitudes = $aptRepo->findAll();
        $interests = $interestRepo->findBy([], ['list_order' => 'ASC']);
        $contacts = $contactRepo->findAll();
        $portfolios_pro = $portfolioRepo->findBy(['type' => 'pro'], ['list_order' => 'ASC']);
        $portfolios_perso = $portfolioRepo->findBy(['type' => 'perso'], ['list_order' => 'ASC']);
        $softs = $softRepo->findAll();
        $languages = $langRepo->findAll();
        
        return $this->render('main/pdf.html.twig', [
            'info' => $info,
            'experiences' => $experiences,
            'trainings' => $trainings,
            'skills' => $skills,
            'aptitudes' => $aptitudes,
            'interests' => $interests,
            'contacts' => $contacts,
            'portfolios_pro' => $portfolios_pro,
            'portfolios_perso' => $portfolios_perso,
            'softs' => $softs,
            'languages' => $languages,
        ]);
    }

        /**
     * @Route("/logout", name="app_logout")
     */
    public function logout()
    {
        throw new \Exception('This method can be blank - it will be intercepted by the logout key on your firewall');
    }
}

templates/main/_aptitudes.html.twig
{% if aptitudes is defined and aptitudes|length > 0 %}
    <section id="expertises__techno" class="expertise">
        <h2 class="expertise__title">TECHNOLOGIES</h2>

        <div class="expertise__desc">
            {% for aptitude in aptitudes %}
                <button type="button" class="btn {{ (app.request.get('_route') ends with 'pdf') ? 'btn-outline-primary' : 'btn-outline-warning' }} skill__button" disabled>{{ aptitude.name }}</button>
            {% endfor %}
        </div>

    </section>
{% endif %}

templates/main/_experiences.html.twig
{% if experiences is defined and experiences|length > 0 %}
    <section class="resume__experiences" id="resume__experience">
        <h1 class="resume__title">Expériences</h1>

        {% for experience in experiences %}
            <section class="experiences__experience">
                <h2 class="resume__subtitle">{{ experience.title }}</h2>
                <h2 class="resume__company">
                    {% if experience.companyLink is defined %}
                        <a href="{{ experience.companyLink }}" class="resume__link" target="_blank" rel="noopener noreferrer">{{ experience.company }}</a> {{ (app.request.get('_route') ends with 'pdf') ? ("<span class='text-muted'><small> - " ~ experience.companyLink ~ "</small></span>") | raw : ''  }}
                    {% else %}
                        {{ experience.company }}
                    {% endif %}
                </h2>

                <p class="resume__date">
                    <i class="fas fa-calendar"></i> 
                    <span>{{ experience.dateStart|date("m/Y") }} - {{ experience.datEend|date("m/Y") }}</span>
                    <i class="fas fa-map-marker-alt"></i> 
                    <strong>{{ experience.location }}</strong>
                </p>

                <p class="resume__desc">
                    {{ experience.description | raw }}
                </p>
            </section>
        {% endfor %}
    </section>
{% endif %}

templates/main/_header.html.twig
<header class="header">
    <div class="header__desc">
        <h1 class="desc__title">{{ info.name is defined ? info.name : 'Name placeholder' }}</h1>
        <h2 class="desc__subtitle">{{ info.title is defined ? info.title : 'Title placeholder' }}</h2>

        {% if contacts is defined and contacts|length > 0 %}
            <div class="desc__contact">
                {% for contact in contacts %}
                    {% if contact.link matches '/^[^\W][a-zA-Z0-9_]+(\.[a-zA-Z0-9_]+)*\@[a-zA-Z0-9_]+(\.[a-zA-Z0-9_]+)*\.[a-zA-Z]{2,4}$/' %}
                        <p class="contact__text"><i class="{{ contact.icon }}"></i> <a href="mailto:{{ contact.link }}" target="_blank" rel="noopener noreferrer">{{ (app.request.get('_route') ends with 'pdf') ? contact.link : contact.name }}</a></p>
                    {% elseif contact.link is null %}
                        <p class="contact__text"><i class="{{ contact.icon }}"></i> {{ contact.name }}</p>
                    {% else %}
                        <p class="contact__text"><i class="{{ contact.icon }}"></i> <a href="{{ contact.link }}" target="_blank" rel="noopener noreferrer">{{ (app.request.get('_route') ends with 'pdf') ? contact.link : contact.name }}</a></p>
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}

    </div>
    
    {% if info.photo is defined %}
        <div class="header__photo"><img src="{{ asset('uploads/photo/' ~ info.photo) }}" alt="Photo de Cédric" class="desc__photo"></div>
    {% else %}
        <div class="header__photo"><img src="" alt="Photo de Cédric" class="desc__photo"></div>
    {% endif %}
</header>

templates/main/_interests.html.twig
{% if interests is defined and interests|length > 0 %}
    <section id="expertises__interests" class="expertise">
        <h2 class="expertise__title">INTÉRÊTS</h2>

        <div class="expertise__desc">
            {% for interest in interests %}
                <p><i class="{{ interest.icon }}"></i> &nbsp;&nbsp; {{ interest.name }}</p>
            {% endfor %}
        </div>

    </section>
{% endif %}

templates/main/_languages.html.twig
{% if languages is defined and languages|length > 0 %}
    <section id="expertise__lang" class="expertise">
        <h2 class="expertise__title">LANGUES</h2>

        <div class="expertise__desc">
            {% for language in languages %}
                <div class="lang__desc">
                    <div class="lang__text">
                        <p class="lang__title">{{ language.name }}</p>
                        <p class="lang__level-text">{{ language.description }}</p>
                    </div>

                    <div class="lang__graph">
                        <p class="graph__level">
                            {% for i in 1..5 %}
                            {% if i <= language.level %}
                            <i class="fas fa-circle"></i>
                            {% else %}
                            <i class="far fa-circle"></i>
                            {% endif %}
                        {% endfor %}
                        </p>
                    </div>
                    
                </div>
            {% endfor %}
        </div>

    </section>
{% endif %}

templates/main/_portfolios_perso.html.twig
{% if portfolios_perso is defined and portfolios_perso|length > 0 %}
    <section id="resume__projects" class="resume__projects">
        <h1 class="resume__title">Portfolio Personnel</h1>

        <div class="personnal_projects">
            {% for portfolio in portfolios_perso %}
                <div class="project">
                    <h3 class="resume__subtitle">{{ portfolio.name }}</h3>
                    <div>{{ portfolio.description | raw }}</div>
                </div>
            {% endfor %}
        </div>
        
    </section>
{% endif %}

templates/main/_portfolios_pro.html.twig
{% if portfolios_pro is defined and portfolios_pro|length > 0 %}
    <section id="resume__projects" class="resume__projects">
        <h1 class="resume__title">Portfolio Professionnel</h1>

        <section class="projects__gallery">

            {% for portfolio in portfolios_pro %}
                {% set regex = '{(https:\/\/www.youtube.com\/|https:\/\/youtu.be\/)}'  %}

                <figure class="gallery__figure">
                    {% if portfolio.description is defined and portfolio.description matches regex  %}
                        <a href="#" data-toggle="modal" data-target="#videoModal" data-content="{{ portfolio.description }}">
                    {% endif %}

                    <img src="{{ asset(portfolio_directory ~ portfolio.image) }}" alt="Image {{ portfolio.name }}" class="gallery__image">

                    {% if portfolio.description is defined and portfolio.description matches regex  %}
                        </a>
                    {% endif %}

                    <figcaption class="gallery__figcaption">{{ portfolio.caption }}</figcaption>
                </figure>
            {% endfor %}
            
        </section>

    </section>
{% endif %}

templates/main/_skills.html.twig
{% if skills is defined and skills|length > 0 %}
    <section id="expertises__skills" class="expertise">
        <h2 class="expertise__title">COMPÉTENCES</h2>

        <div class="expertise__desc">
            {% for skill in skills %}
                <div class="expertise__skill">
                    <p class="skill__title">{{ skill.name }}</p>

                    <p class="skill__level">
                        {% for i in 1..5 %}
                            {% if i <= skill.level %}
                                <i class="fas fa-circle"></i>
                            {% else %}
                                <i class="far fa-circle"></i>
                            {% endif %}
                        {% endfor %}
                    </p>
                    
                </div>
            {% endfor %}
        </div>

    </section>
{% endif %}

templates/main/_softs.html.twig
{% if softs is defined and softs|length > 0 %}
    <section id="expertises__soft-skill" class="expertise">
        <h2 class="expertise__title">SOFT-SKILLS</h2>

        <div class="expertise__desc">
            {% for soft in softs %}
                <button type="button" class="btn {{ (app.request.get('_route') ends with 'pdf') ? 'btn-outline-primary' : 'btn-outline-warning' }} skill__button" disabled>{{ soft.name }}</button>
            {% endfor %}
        </div>
        
    </section>
{% endif %}

templates/main/_trainings.html.twig
{% if trainings is defined and trainings|length > 0 %}
    <section id="resume__formations" class="resume__formation">
        <h1 class="resume__title">Formations</h1>

        {% for training in trainings %}
            <section class="formations__formation">
                <h2 class="resume__subtitle">{{ training.title }}</h2>
                <h3 class="resume__company">
                    {% if training.companyLink != '' %}
                    <a href="{{ training.companyLink }}" class="resume__link" target="_blank" rel="noopener noreferrer">{{ training.company }}</a>  {{ (app.request.get('_route') ends with 'pdf') ? ("<span class='text-muted'><small> - " ~ training.companyLink ~ "</small></span>") | raw : ''  }}
                    {% else %}
                        {{ training.company }}
                    {% endif %}
                </h3>

                <p class="resume__date">
                    <i class="fas fa-calendar"></i> 
                    <span>{{ training.dateStart|date("m/Y") }} - {{ training.dateEnd|date("m/Y") }}</span>
                    <i class="fas fa-map-marker-alt"></i> 
                    <strong>{{ training.location }}</strong>
                </p>

                <p class="resume__desc">
                    {{ training.description | raw }}
                </p>
            </section>
        {% endfor %}

    </section>
{% endif %}

templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('assets/css/style.css') }}">
{% endblock %}

{% block body %}
<div class="container">
    {% include 'main/_header.html.twig' %}

    <main>
        <section class="resume">

            {% include 'main/_experiences.html.twig' %}

            {% include 'main/_portfolios_pro.html.twig' %}

            {% include 'main/_portfolios_perso.html.twig' %}

            {% include 'main/_trainings.html.twig' %}
        </section>

        <section class="expertises">

            {% include 'main/_skills.html.twig' %}

            {% include 'main/_aptitudes.html.twig' %}

            {% include 'main/_softs.html.twig' %}

            {% include 'main/_languages.html.twig' %}

            {% include 'main/_interests.html.twig' %}
        </section>

        <div class="modal fade" id="videoModal" tabindex="-1" role="dialog" aria-labelledby="videoModalTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="videoModalTitle">Description</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    
                    <div class="modal-body">
                        <iframe width="100%" height="433" src="" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    </main>

    <footer class="text-center">
        <div>
            <a href="{{ path('home_pdf') }}" rel="noopener noreferrer">View the print version</a>
        </div>
    </footer>
</div>
{% endblock %}

{% block javascript %}
<script src="{{ asset('assets/js/app.js') }}"></script>
{% endblock %}

templates/main/pdf.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('assets/css/style.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/pdf.css') }}">
{% endblock %}

{% block body %}
<div class="container">
    {% include 'main/_header.html.twig' %}

    <main>
        <section class="resume">

            {% include 'main/_experiences.html.twig' %}

            {% include 'main/_portfolios_pro.html.twig' %}

            {% include 'main/_portfolios_perso.html.twig' %}

            {% include 'main/_trainings.html.twig' %}
        </section>

        <section class="expertises">

            {% include 'main/_skills.html.twig' %}

            {% include 'main/_aptitudes.html.twig' %}

            {% include 'main/_softs.html.twig' %}

            {% include 'main/_languages.html.twig' %}

            {% include 'main/_interests.html.twig' %}

            <section id="expertises_particularities" class="expertise">
                <h2 class="expertise__title">PARTICULARITÉS</h2>
                <div class="expertise__desc">
                    <p>
                        <a name="surdoue" id="surdoue" class="btn btn-outline-primary" href="https://www.davidsongifted.org/Search-Database/entry/A10495" target="_blank" rel="noopener noreferrer" role="button">Surefficient mental</a>
                    </p>
                </div>
            </section>
        </section>

        <div class="modal fade" id="videoModal" tabindex="-1" role="dialog" aria-labelledby="videoModalTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="videoModalTitle">Description</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    
                    <div class="modal-body">
                        <iframe width="100%" height="433" src="" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>
{% endblock %}

{% block javascript %}
<script src="{{ asset('assets/js/app.js') }}"></script>
{% endblock %}